/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexion;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanKuzo
 */
public class AgregarTablas extends javax.swing.JFrame {

    /**
     * Creates new form AgregarTablas
     */
    public AgregarTablas() {
        initComponents();
        mostarDatos(buscarId.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtCod = new javax.swing.JTextField();
        txtDes = new javax.swing.JTextField();
        txtPre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grabar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        buscarId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ruta = new javax.swing.JTextField();
        selecciona = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();

        jMenuItem1.setText("modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.setComponentPopupMenu(jPopupMenu1);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba de base de datos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles Producto"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 74, 150, -1));
        jPanel1.add(txtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 123, 150, -1));

        txtPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreActionPerformed(evt);
            }
        });
        jPanel1.add(txtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 179, 150, -1));

        jLabel1.setText("Codigo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 77, -1, -1));

        jLabel2.setText("Descricion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 126, -1, -1));

        jLabel3.setText("Precio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 182, -1, -1));

        grabar.setText("Grabar");
        grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarActionPerformed(evt);
            }
        });
        jPanel1.add(grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jButton1.setText("Probar Conexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 43, 150, 20));

        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 46, -1, 10));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));
        jPanel1.add(buscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, -1));

        jLabel5.setText("Buscar Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel6.setText("Imagen");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        jPanel1.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 150, -1));

        selecciona.setText("Seleccionar");
        selecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionaActionPerformed(evt);
            }
        });
        jPanel1.add(selecciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 150, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 280));
        jPanel1.getAccessibleContext().setAccessibleName("Detalles por\n");

        tbProductos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 560, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreActionPerformed

    private void grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarActionPerformed
        try {
            FileInputStream archivofoto;
            archivofoto = new FileInputStream(ruta.getText());
            PreparedStatement pst = cn.prepareStatement("INSERT INTO productos (idProducto, codPro, desPro, prePro, NomImagen, imagen) VALUES (NULL,?,?,?,?,?)");
            pst.setString(1, txtCod.getText());
            pst.setString(2, txtDes.getText());
            pst.setString(3, txtPre.getText());
            pst.setString(4, ruta.getText());
            pst.setBinaryStream(5, archivofoto);
            pst.executeUpdate();
            mostarDatos(buscarId.getText());
        } catch (Exception e) {
            System.out.println("Error en insertat " + e.getMessage());
        }

    }//GEN-LAST:event_grabarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cn == null) {
            System.out.println("no conectado");
        } else {
            System.out.println("conectado ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        mostarDatos(buscarId.getText());
    }//GEN-LAST:event_buscarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int filas = tbProductos.getSelectedRow();
        System.out.println("valor filas: " + filas);
        if (filas >= 0) {
            id.setText(tbProductos.getValueAt(filas, 0).toString());
            txtCod.setText(tbProductos.getValueAt(filas, 1).toString());
            txtDes.setText(tbProductos.getValueAt(filas, 2).toString());
            txtPre.setText(tbProductos.getValueAt(filas, 3).toString());
            String ruta2 = (tbProductos.getValueAt(filas, 4).toString());
            ruta.setText(ruta2);
            System.out.println(ruta2);
            Image foto = getToolkit().getImage(ruta2);
            foto = foto.getScaledInstance(110, 110, 1);
            imagen.setIcon(new ImageIcon(foto));
        } else {
            JOptionPane.showMessageDialog(null, "No hay filas seleccionadas");
        }
        id.setEnabled(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fila = tbProductos.getSelectedRow();
        String idEliminar = "";
        idEliminar = tbProductos.getValueAt(fila, 0).toString();
        try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM `productos` WHERE `idProducto` =" + idEliminar + "");
            pst.executeUpdate();
            mostarDatos("");
        } catch (Exception e) {
            System.out.println("Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try {
            FileInputStream archivofoto;
            File nombre = new File(ruta.getText());
            archivofoto = new FileInputStream(nombre);
            String update = "UPDATE productos SET"
                    + " codPro='" + txtCod.getText()
                    + "', desPro='" + String.valueOf(txtDes.getText())
                    + "', prePro='" + txtPre.getText() + "', NomImagen=?, imagen=? WHERE idProducto=" + id.getText() + "";
            System.out.println(update);
            PreparedStatement pst = cn.prepareStatement(update);
            archivofoto = new FileInputStream(ruta.getText());
            pst.setString(1, ruta.getText());
            pst.setBinaryStream(2, archivofoto);
            pst.executeUpdate();
            mostarDatos("");
        } catch (Exception e) {
            System.out.println("Error al actualizar " + e.getMessage());
        }
        limpiar();
        id.setEnabled(true);
    }//GEN-LAST:event_actualizarActionPerformed

    private void seleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionaActionPerformed
        JFileChooser archivo = new JFileChooser();
        int ventana = archivo.showOpenDialog(null);

        if (ventana == JFileChooser.APPROVE_OPTION) {
            File file = archivo.getSelectedFile();
            ruta.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(ruta.getText());
            foto = foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            imagen.setIcon(new ImageIcon(foto));

        }
    }//GEN-LAST:event_seleccionaActionPerformed
    void limpiar() {
        txtCod.setText(" ");
        txtDes.setText(" ");
        txtPre.setText(" ");
        id.setText(" ");
        buscarId.setText("");
        ruta.setText("");
        imagen.setText("");
    }

    void mostarDatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("mamadas");
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Ruta");
        modelo.addColumn("imagen");

        tbProductos.setModel(modelo);
        String sql = "";
//        if (valor.equals("")) {
//            sql = "SELECT * FROM `productos`";
//        } else {
//            sql = "SELECT * FROM `productos` WHERE idProducto =" + valor + "";
//        }
//        String[] datos = new String[6];
//        try {
//            Statement st = cn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            while (rs.next()) {
//                datos[0] = rs.getString(1);
//                datos[1] = rs.getString(2);
//                datos[2] = rs.getString(3);
//                datos[3] = rs.getString(4);
//                datos[4] = rs.getString(5);
//                datos[5] = rs.getString(6);
//                modelo.addRow(datos);
//            }
//            tbProductos.setModel(modelo);
//        } catch (SQLException ex) {
//            System.out.println("Error " + ex);
//        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarId;
    private javax.swing.JButton grabar;
    private javax.swing.JTextField id;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ruta;
    private javax.swing.JButton selecciona;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtPre;
    // End of variables declaration//GEN-END:variables
Conectar cc = new Conectar();
    Connection cn = cc.conexion();
}
